import { Inter } from 'next/font/google'
import './globals.css'
import {Toaster }from 'react-hot-toast';
const inter = Inter({ subsets: ['latin'] })
import NextUIProviders from './providers'
export const metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <NextUIProviders>
          <Toaster />
        {children}
        </NextUIProviders>
        </body>
    </html>
  )
}
